### ISSUE TITLE
Clang and noexcept

### ISSUE THREAD

**Issue by degski** [HDembinski/essays#1]
Nice write-up.

Clang-10 does not blindly trust the `noexcept` specifier and warns at compile-time. It also finds (warns on) destructors that (transitively) throw, while not being marked `noexcept(false)`.

d.

**Comment by HDembinski** [comment]
Hi degski, thank you for this detail and for reading my essay! I will fix it.

**Comment by HDembinski** [comment]
I clarified this in the text. It turns out that I was not wrong, both gcc and clang detect the obvious case, but it is sufficient to wrap the throw in a nested function to get "rid" of the warning.
