### ISSUE TITLE
2nd. noexcept might be harmful

### ISSUE THREAD

**Issue by expnkx** [HDembinski/essays#3]
https://www.youtube.com/watch?v=dVRLp-Rwg0k

**Comment by HDembinski** [comment]
Thanks! Unfortunately I had to watch all of that only for the last slide. I would not conclude that `noexcept` was mismarketed, but rather that the old compilers which he tested did not support `noexcept` very well yet. gcc seems to do well. VS is generally running behind gcc and clang in supporting new C++ features and optimisations.

I added a remark and link to N-Dekker's benchmark.
