### ISSUE TITLE
run-time cost of exceptions

### ISSUE THREAD

**Issue by arvidn** [HDembinski/essays#5]
> All in all, this has a noticeable effect even in carefully written libraries that use exceptions. In Boost.Histogram, benchmarks run 10-15 % faster when I deactivate exceptions with -fno-exceptions, even though no exceptions are thrown in these benchmarks.

I think it's important to remember that the main difference between `-fexceptions` and `-fno-exceptions` here is really that you disable all *error handling*.

Presumably, the optimization opportunities would still not be there if all error paths were still in place, but via a return value instead.

**Comment by expnkx** [comment]
why do people keep bitching about the exception's runtime cost instead of trying to implement Herbception for GCC?

**Comment by HDembinski** [comment]
This is not correct. In Boost.Histogram and in the GCC implementation of the stdlib, [turning off exceptions causes the stdlib to fail fast when an exception would be thrown](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html). While this is not error handling, it is still error reporting. There is a path in the code which reports the error when it occurs.

**Comment by arvidn** [comment]
sure, call it error reporting.
I'm suggesting that the majority of the performance gains *in the happy path* you get from disabling exceptions has nothing to do with exceptions, it's because you disable error reporting.

**Comment by HDembinski** [comment]
How should the path that is not taken affect the run-time performance of the code, then?

**Comment by arvidn** [comment]
I'm not sure I'm following. In one case you have two return paths (with exceptions), in the other you have one (just the normal return), so that give the optimizer more opportunities to reorder things.

With two return paths destructors may have to be ordered more strictly and called more eagerly for instance. Registers may have to spill more frequently. Every path that can exit with an exception will add constraints like that, just like checking an error code an possibly returning an error would.
