### ISSUE TITLE
sympy does not seem to have parse_expr

### ISSUE THREAD

**Issue by acampove** [HDembinski/essays#6]
Hi,

In:

https://github.com/HDembinski/essays/blob/master/error_propagation_with_sympy.ipynb

you do:

```python
sympy.parse_expr(expr)
```
However I get:

![image](https://user-images.githubusercontent.com/14037062/122395085-39bc5a80-cfa9-11eb-9b51-0eb67b394a43.png)

And here:

https://docs.sympy.org/latest/modules/parsing.html

I see:

![image](https://user-images.githubusercontent.com/14037062/122395191-522c7500-cfa9-11eb-9ced-2589feaa87be.png)

which suggests that this module changed and/or there is a problem with the function. I tested a modified version:

![image](https://user-images.githubusercontent.com/14037062/122396130-442b2400-cfaa-11eb-8ec9-4bded1845fcb.png)

and I got it to work again. The changes are in lines 3 and 6.

Cheers.

**Comment by HDembinski** [comment]
Thanks for the comment/solution :)

**Comment by HDembinski** [comment]
I checked again that I have the latest version of Sympy 1.8, and there `sympy.parse_expr` works as in my write-up. Perhaps you have an older version of Sympy? Sympy imports a lot of functions from submodules into the top-level module, so your solution works as well, but requires that the user knows where to find the `parse_expr` function. In light of that, I will stick to my code for now.
