### ISSUE TITLE
Computation in "Error propagation with Sympy"

### ISSUE THREAD

**Issue by alessandro-gentilini** [HDembinski/essays#9]
Hello,
it seems to me that the line

`expr2 = sum(expr.diff(s) ** 2 * c for s, c in zip(symbols, cov_symbols))`

is not properly computing the expression; in particular the `c` should be squared too and the square root is missing (I use https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Simplification as a reference).

So in my opinion the line should be:

`expr2 = sum((expr.diff(s) *c) ** 2 for s, c in zip(symbols, cov_symbols))**.5`

**Comment by HDembinski** [comment]
Hi, thanks for your interest and the critical reading, but I think the calculation is correct. I claim that `value_and_covariance` computes the covariance, not the standard deviation. The reference you cite computes the standard deviation which is the square root of the (co)variance.
